name: 'Build Tag Number'
description: 'Sequential build numbers for workflow runs based on Git tag'
author: 'Mano176'
runs:
  using: 'node20'
  main: 'main.js'
inputs:
  token:
    description: 'GitHub Token to create and delete refs (GITHUB_TOKEN)'
    required: false # Not required when getting the stored build number for later jobs, only in the first jobs when it's generated
  version_number:
    description: 'Version number'
    required: true

outputs:
  build_number:
    description: 'Build tag number'

branding:
  icon: 'hash'
  color: 'green'
